### ISSUE TITLE
Triplet Loss ForwardPropogate

### ISSUE THREAD

**Issue by kikoo321** [WICWIU/WICWIU#17]
I don't know the meaning of line 118 & 120 in 'TripletLoss.hpp'
Please let me knowㅠㅠ

**Comment by cmpark0126** [comment]
https://github.com/WICWIU/WICWIU/blob/5e4102c92e8fae94a3abfecd56214e7e08a66256/WICWIU_src/LossFunction/TripletLoss.hpp#L118

https://github.com/WICWIU/WICWIU/blob/5e4102c92e8fae94a3abfecd56214e7e08a66256/WICWIU_src/LossFunction/TripletLoss.hpp#L120

**Comment by cmpark0126** [comment]
In case line 118, this line store 1 into m_LossPerSample. It means this case needs backprop algo.

It will be used in line 150 like below,

https://github.com/WICWIU/WICWIU/blob/5e4102c92e8fae94a3abfecd56214e7e08a66256/WICWIU_src/LossFunction/TripletLoss.hpp#L150

if it has 1, this line will be execute the codes in if statement code block, and it will calculate the gradient with related anchor, positive and negative sample. 

In case of line 120 similar reason, I think you can assume why it store 0.

Good luck!

**Comment by kikoo321** [comment]
Thanks^^
