### ISSUE TITLE
LossFunction debugging by cgdb

### ISSUE THREAD

**Issue by osj3474** [WICWIU/WICWIU#18]
![1](https://user-images.githubusercontent.com/42775225/62860578-87c3ff80-bd3b-11e9-9cea-93339dcc6e54.PNG)

Why can't I access the 'Trian' function by 's'?
--------------------------------------------------
cgdb로 segmentation fault 잡으려고 하는데, 정확히 에러 나는 부분이 어디인지 확인하고 싶은데 s눌러도 함수 안으로 못 들어가네요.. 혹시 아시는 분 계신가요?

**Comment by JinMyeongSuh** [comment]
I wanna know that, too! :))

**Comment by cmpark0126** [comment]
Could you attach full screen shot has all command history related to cgdb?

**Comment by cmpark0126** [comment]
There is no question anymore, I will close this issue. If you have additional question related to this issue, please reopen it. Thank you.
