### ISSUE TITLE
Question about AnalyzeGraph in Module class

### ISSUE THREAD

**Issue by junseokoh1** [WICWIU/WICWIU#19]
1. preOp->Pop(out)
preOp 포인터를 사용해서 m_apOutput이 가리키는 배열과 같은 것을 가리키도 있는 것으로 이해했습니다. (배열의 복사가 아닌 주소값을 가져오는 것으로 이해했습니다.) 그렇게 된다면 preOp->Pop(out)을 하면 preOp 가리키고있는 m_apOutput배열에서 out에 해당하는 Operator와의 연결을 끊는 것으로 해석이 됩니다. 이렇게 그래프의 구조를 바뀌는 것이 맞나요?...
2. this->AnalyzeGraph(out)
my_CNN에 있는 ConvolutionLayer2D class와 Linear class에서 각각 Alloc에서 this->AnalyzeGraph(out)을 호출하는 것으로 확인 했습니다. 
근데 my_CNN에서 맨 마지막에 AnalyzeGraph(out)을 호출합니다. 제가 이해한것은 각각의 class에서 analyzeGraph를 호출한 것은 큰 의미가 없고 my_CNN class에서 맨 마지막에 AnalyzeGraph(out)만 의미가 있으면 이때 정해지는 m_aaExcutableOperator와 m_apParameter 배열을 사용해서 학습하는게 맞나요???

**Comment by cmpark0126** [comment]
Please re-write the question with exact code link. 

You can refer a specific code line when you write a comment on git issue.

For example, you can able to attach code when you write the question 2 like this:

https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module/ConvolutionLayer.hpp#L90

https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/tutorials/MNIST/net/my_CNN.hpp#L37

Link like above is called permalink, and you can get this link on the left-hand side of code line which you want to refer. 

Thank you.

**Comment by cmpark0126** [comment]
![image](https://user-images.githubusercontent.com/17241893/62867135-81d71a00-bd4d-11e9-8618-46b5a19adc55.png)

**Comment by junseokoh1** [comment]
1. preOp->Pop(out)
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module.hpp#L309
preOp 포인터를 사용해서 m_apOutput이 가리키는 배열과 같은 것을 가리키도 있는 것으로 이해했습니다. (배열의 복사가 아닌 주소값을 가져오는 것으로 이해했습니다.)
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module.hpp#L308
그렇게 된다면 preOp->Pop(out)을 하면 preOp 가리키고있는 m_apOutput배열에서 out에 해당하는 Operator와의 연결을 끊는 것으로 해석이 됩니다. 이렇게 그래프의 구조를 바뀌는 것이 맞나요?...
그리고 Pop을 하는 이유가 그래프 탐색을 위한건가요?
2. this->AnalyzeGraph(out)
my_CNN에 있는 ConvolutionLayer2D class와 Linear class에서 각각 Alloc에서 this->AnalyzeGraph(out)을 호출하는 것으로 확인 했습니다.
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module/ConvolutionLayer.hpp#L90
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module/LinearLayer.hpp#L56
근데 my_CNN에서 맨 마지막에 AnalyzeGraph(out)을 호출합니다. 
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/tutorials/MNIST/net/my_CNN.hpp#L37
제가 이해한것은 각각의 class에서 analyzeGraph를 호출한 것은 큰 의미가 없고 my_CNN class에서 맨 마지막에 AnalyzeGraph(out)만 의미가 있으면 이때 정해지는 m_aaExcutableOperator와 m_apParameter 배열을 사용해서 학습하는게 맞나요???

**Comment by cmpark0126** [comment]
1. 코드의 동작을 고려해보았을 때, 저 과정이 없어도 될 것 같습니다. 

https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module.hpp#L309

위의 부분을 빼고 컴파일 했을 때 문제가 있는지 한 번 확인해봐주세요. 

그리고 여기에서 Pop을 했을 경우 그래프의 구조가 변화하는 것이 맞습니다. 하지만 WICWIU의 경우는 Operator간의 edge가 중요한 파트는 AnalyzeGraph를 할 때 뿐이기 때문에, 추후 동작에는 전혀 영향을 주지 않습니다.

https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module.hpp#L298-L302

실제 그래프 구조는 위에서 결정됩니다.

ps. 현재 WICWIU에서는 m_apOutput이 실제 동작에서 액티브하게 사용되지 않습니다. (설계 변화로 인해)

2. 아니요. 중요합니다.

현재 WICWIU의 그래프 구조는 recursively 정의 됩니다. 

![image](https://user-images.githubusercontent.com/17241893/62909447-9fd96480-bdb7-11e9-9b8c-ccc8f5c9e38f.png)

위의 그림에서 Module은 ConvolutionLayer2D class와 Linear class과 같은 Class를 의미합니다. 다만 그리고 전체 NeuralNetwork는 my_CNN class 입니다. 이 때, 우리는 그래프 구조를 정확히 알기 때문에 위의 그림에서도 Module은 여러개의 Operator를 가지고 있다는 것을 알고 있지만, 실제로 my_CNN class는 Module이나 Operator 모두 각각의 Operator로 인식하기 때문에, Module 내부의 Operator를 탐색하지 않습니다. 그렇기 때문에 Module은 자기 내부에 있는 Operator에 대한 분석을 따로 진행해둬야 내부에서 recursively 사용이 가능합니다. 

그렇기 때문에 각각의 class에서 analyzeGraph를 호출한 것은 매우 중요합니다.

cc. @osj3474 @JinMyeongSuh

**Comment by junseokoh1** [comment]
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module.hpp#L309
이 부분을 제거해도 추후 동작에 영향을 주지 않습니다!

**Comment by cmpark0126** [comment]
Great. Commit modified version. I will close this issue. If you have additional question associated with this issue, please re-open. thank you.
