### ISSUE TITLE
Question about implementing RNN

### ISSUE THREAD

**Issue by junseokoh1** [WICWIU/WICWIU#20]
RNN 구현관련 질문을 남깁니다.
먼저 my_CNN과 ConvolutionLayer2D을 비교하면서 RNN을 생각해보았습니다.
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/tutorials/MNIST/net/my_CNN.hpp#L6
my_CNN은 NeuralNetwork를 상속하고 있으며
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module/ConvolutionLayer.hpp#L34
ConvolutionLayer2D는 Module을 상속하고 있습니다.

이와 마찬가지로  NeuralNetwork를 상속하는 my_RNN과 Module을 상속하는 RNNLayer를 만들 생각입니다.

근데 RNN 계산을 해주는 Operator가 필요한지에 대한 의견이 모이지 않아 이렇게 남깁니다.

1. Without RNN operator
사실 RNN 구현에 필요한 operator인 tanh와 MatMul이 이미 있기때문에 RNNLayer에서 
https://github.com/WICWIU/WICWIU/blob/9a60b8cd160c0079933a8beca86bca4b053de0a2/WICWIU_src/Module/ConvolutionLayer.hpp#L82
위와 같이 Tensorholder<DTYPE>를 만들어서 필요한 연산만 하면 됩니다. 이렇게 구현이 가능하다는 의견입니다.

2. With RNN Operator
MatMul과 tanh를 다 모아서 RNN 연산을 한번에 해주는 Operator를 만들자는 의견입니다.
이 의견이 나온 가장 큰 이유는 cudnn입니다. cudnn 코드를 추가하기 위해서는 Operator에 있는 forward와 backward 함수가 필요하기 때문입니다.

2번째 안건입니다.
NeuralNetwork 단위를 1번으로 할지 2번으로 할지 문의 드립니다.

![KakaoTalk_20190814_213622326](https://user-images.githubusercontent.com/28286337/63021560-d01a2380-bedb-11e9-801f-e13f07ec63f8.png)

comment 남겨주시면 감사하겠습니다

**Comment by junseokoh1** [comment]
There is no authority to change label to me

**Comment by osj3474** [comment]
The first question is that we are concerned about adding cuDNN code for cuDNNRNNForward because we can find cuDNN code in Operator low class, not Module low class.

**Comment by osj3474** [comment]
We received the answer of these problems from Professor Kim. 

In first matter of RNN class inheritance, he recommended  _class RNNcell : public Module_, 
and just cuDNN code in _class RNN : public Operator_.

In second matter of selecting NeuralNet unit, second case is the best because of expanding LSTM, etc.

Thank you for considering the problem:)

**Comment by cmpark0126** [comment]
I don't have any ideas about it. It depends your decision. 
I cannot advice to future implementation. 

Thank you.
